FROM debian:bookworm-slim
RUN set -ex \
    && apt-get update \
    && apt-get install -y ca-certificates tzdata nftables wireguard-tools \
    && rm -rf /var/lib/apt/lists/*

COPY sing-box-extensions /usr/local/bin/lantern-box

ENTRYPOINT ["/usr/local/bin/lantern-box", "run", "--config", "/config.json"]
