// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: tracker/datacap/dcpb/datacap.proto

package dcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataCapUsageBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*DataCapUsage        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCapUsageBatch) Reset() {
	*x = DataCapUsageBatch{}
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCapUsageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCapUsageBatch) ProtoMessage() {}

func (x *DataCapUsageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCapUsageBatch.ProtoReflect.Descriptor instead.
func (*DataCapUsageBatch) Descriptor() ([]byte, []int) {
	return file_tracker_datacap_dcpb_datacap_proto_rawDescGZIP(), []int{0}
}

func (x *DataCapUsageBatch) GetRecords() []*DataCapUsage {
	if x != nil {
		return x.Records
	}
	return nil
}

type DataCapUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	BytesUsed     int64                  `protobuf:"varint,2,opt,name=bytesUsed,proto3" json:"bytesUsed,omitempty"`
	CapLimit      int64                  `protobuf:"varint,3,opt,name=capLimit,proto3" json:"capLimit,omitempty"`
	CountryCode   string                 `protobuf:"bytes,5,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	Platform      string                 `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCapUsage) Reset() {
	*x = DataCapUsage{}
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCapUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCapUsage) ProtoMessage() {}

func (x *DataCapUsage) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCapUsage.ProtoReflect.Descriptor instead.
func (*DataCapUsage) Descriptor() ([]byte, []int) {
	return file_tracker_datacap_dcpb_datacap_proto_rawDescGZIP(), []int{1}
}

func (x *DataCapUsage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DataCapUsage) GetBytesUsed() int64 {
	if x != nil {
		return x.BytesUsed
	}
	return 0
}

func (x *DataCapUsage) GetCapLimit() int64 {
	if x != nil {
		return x.CapLimit
	}
	return 0
}

func (x *DataCapUsage) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *DataCapUsage) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type ReportUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*UsageResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUsageResponse) Reset() {
	*x = ReportUsageResponse{}
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUsageResponse) ProtoMessage() {}

func (x *ReportUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUsageResponse.ProtoReflect.Descriptor instead.
func (*ReportUsageResponse) Descriptor() ([]byte, []int) {
	return file_tracker_datacap_dcpb_datacap_proto_rawDescGZIP(), []int{2}
}

func (x *ReportUsageResponse) GetResults() []*UsageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type UsageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageResult) Reset() {
	*x = UsageResult{}
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageResult) ProtoMessage() {}

func (x *UsageResult) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageResult.ProtoReflect.Descriptor instead.
func (*UsageResult) Descriptor() ([]byte, []int) {
	return file_tracker_datacap_dcpb_datacap_proto_rawDescGZIP(), []int{3}
}

func (x *UsageResult) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UsageResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UsageResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DataCapSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCapSyncRequest) Reset() {
	*x = DataCapSyncRequest{}
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCapSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCapSyncRequest) ProtoMessage() {}

func (x *DataCapSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCapSyncRequest.ProtoReflect.Descriptor instead.
func (*DataCapSyncRequest) Descriptor() ([]byte, []int) {
	return file_tracker_datacap_dcpb_datacap_proto_rawDescGZIP(), []int{4}
}

func (x *DataCapSyncRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DataCapSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	BytesUsed     int64                  `protobuf:"varint,2,opt,name=bytesUsed,proto3" json:"bytesUsed,omitempty"`
	CapLimit      int64                  `protobuf:"varint,3,opt,name=capLimit,proto3" json:"capLimit,omitempty"`
	ExpiryTime    int64                  `protobuf:"varint,5,opt,name=expiryTime,proto3" json:"expiryTime,omitempty"`
	CountryCode   string                 `protobuf:"bytes,6,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	Platform      string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCapSyncResponse) Reset() {
	*x = DataCapSyncResponse{}
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCapSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCapSyncResponse) ProtoMessage() {}

func (x *DataCapSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_datacap_dcpb_datacap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCapSyncResponse.ProtoReflect.Descriptor instead.
func (*DataCapSyncResponse) Descriptor() ([]byte, []int) {
	return file_tracker_datacap_dcpb_datacap_proto_rawDescGZIP(), []int{5}
}

func (x *DataCapSyncResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DataCapSyncResponse) GetBytesUsed() int64 {
	if x != nil {
		return x.BytesUsed
	}
	return 0
}

func (x *DataCapSyncResponse) GetCapLimit() int64 {
	if x != nil {
		return x.CapLimit
	}
	return 0
}

func (x *DataCapSyncResponse) GetExpiryTime() int64 {
	if x != nil {
		return x.ExpiryTime
	}
	return 0
}

func (x *DataCapSyncResponse) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *DataCapSyncResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_tracker_datacap_dcpb_datacap_proto protoreflect.FileDescriptor

const file_tracker_datacap_dcpb_datacap_proto_rawDesc = "" +
	"\n" +
	"\"tracker/datacap/dcpb/datacap.proto\x12\x11lantern_cloud.api\"N\n" +
	"\x11DataCapUsageBatch\x129\n" +
	"\arecords\x18\x01 \x03(\v2\x1f.lantern_cloud.api.DataCapUsageR\arecords\"\xa2\x01\n" +
	"\fDataCapUsage\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\tbytesUsed\x18\x02 \x01(\x03R\tbytesUsed\x12\x1a\n" +
	"\bcapLimit\x18\x03 \x01(\x03R\bcapLimit\x12 \n" +
	"\vcountryCode\x18\x05 \x01(\tR\vcountryCode\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\tR\bplatform\"O\n" +
	"\x13ReportUsageResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.lantern_cloud.api.UsageResultR\aresults\"Y\n" +
	"\vUsageResult\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"0\n" +
	"\x12DataCapSyncRequest\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x01(\tR\bdeviceId\"\xc9\x01\n" +
	"\x13DataCapSyncResponse\x12\x1a\n" +
	"\bdeviceId\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\tbytesUsed\x18\x02 \x01(\x03R\tbytesUsed\x12\x1a\n" +
	"\bcapLimit\x18\x03 \x01(\x03R\bcapLimit\x12\x1e\n" +
	"\n" +
	"expiryTime\x18\x05 \x01(\x03R\n" +
	"expiryTime\x12 \n" +
	"\vcountryCode\x18\x06 \x01(\tR\vcountryCode\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform2\xcf\x01\n" +
	"\x0eDataCapService\x12[\n" +
	"\vReportUsage\x12$.lantern_cloud.api.DataCapUsageBatch\x1a&.lantern_cloud.api.ReportUsageResponse\x12`\n" +
	"\x0fSyncDeviceState\x12%.lantern_cloud.api.DataCapSyncRequest\x1a&.lantern_cloud.api.DataCapSyncResponseB8Z6github.com/getlantern/lantern-box/tracker/datacap/dcpbb\x06proto3"

var (
	file_tracker_datacap_dcpb_datacap_proto_rawDescOnce sync.Once
	file_tracker_datacap_dcpb_datacap_proto_rawDescData []byte
)

func file_tracker_datacap_dcpb_datacap_proto_rawDescGZIP() []byte {
	file_tracker_datacap_dcpb_datacap_proto_rawDescOnce.Do(func() {
		file_tracker_datacap_dcpb_datacap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_datacap_dcpb_datacap_proto_rawDesc), len(file_tracker_datacap_dcpb_datacap_proto_rawDesc)))
	})
	return file_tracker_datacap_dcpb_datacap_proto_rawDescData
}

var file_tracker_datacap_dcpb_datacap_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tracker_datacap_dcpb_datacap_proto_goTypes = []any{
	(*DataCapUsageBatch)(nil),   // 0: lantern_cloud.api.DataCapUsageBatch
	(*DataCapUsage)(nil),        // 1: lantern_cloud.api.DataCapUsage
	(*ReportUsageResponse)(nil), // 2: lantern_cloud.api.ReportUsageResponse
	(*UsageResult)(nil),         // 3: lantern_cloud.api.UsageResult
	(*DataCapSyncRequest)(nil),  // 4: lantern_cloud.api.DataCapSyncRequest
	(*DataCapSyncResponse)(nil), // 5: lantern_cloud.api.DataCapSyncResponse
}
var file_tracker_datacap_dcpb_datacap_proto_depIdxs = []int32{
	1, // 0: lantern_cloud.api.DataCapUsageBatch.records:type_name -> lantern_cloud.api.DataCapUsage
	3, // 1: lantern_cloud.api.ReportUsageResponse.results:type_name -> lantern_cloud.api.UsageResult
	0, // 2: lantern_cloud.api.DataCapService.ReportUsage:input_type -> lantern_cloud.api.DataCapUsageBatch
	4, // 3: lantern_cloud.api.DataCapService.SyncDeviceState:input_type -> lantern_cloud.api.DataCapSyncRequest
	2, // 4: lantern_cloud.api.DataCapService.ReportUsage:output_type -> lantern_cloud.api.ReportUsageResponse
	5, // 5: lantern_cloud.api.DataCapService.SyncDeviceState:output_type -> lantern_cloud.api.DataCapSyncResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tracker_datacap_dcpb_datacap_proto_init() }
func file_tracker_datacap_dcpb_datacap_proto_init() {
	if File_tracker_datacap_dcpb_datacap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_datacap_dcpb_datacap_proto_rawDesc), len(file_tracker_datacap_dcpb_datacap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_datacap_dcpb_datacap_proto_goTypes,
		DependencyIndexes: file_tracker_datacap_dcpb_datacap_proto_depIdxs,
		MessageInfos:      file_tracker_datacap_dcpb_datacap_proto_msgTypes,
	}.Build()
	File_tracker_datacap_dcpb_datacap_proto = out.File
	file_tracker_datacap_dcpb_datacap_proto_goTypes = nil
	file_tracker_datacap_dcpb_datacap_proto_depIdxs = nil
}
