// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: tracker/datacap/dcpb/datacap.proto

package dcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataCapService_ReportUsage_FullMethodName     = "/lantern_cloud.api.DataCapService/ReportUsage"
	DataCapService_SyncDeviceState_FullMethodName = "/lantern_cloud.api.DataCapService/SyncDeviceState"
)

// DataCapServiceClient is the client API for DataCapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataCapServiceClient interface {
	ReportUsage(ctx context.Context, in *DataCapUsageBatch, opts ...grpc.CallOption) (*ReportUsageResponse, error)
	SyncDeviceState(ctx context.Context, in *DataCapSyncRequest, opts ...grpc.CallOption) (*DataCapSyncResponse, error)
}

type dataCapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataCapServiceClient(cc grpc.ClientConnInterface) DataCapServiceClient {
	return &dataCapServiceClient{cc}
}

func (c *dataCapServiceClient) ReportUsage(ctx context.Context, in *DataCapUsageBatch, opts ...grpc.CallOption) (*ReportUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportUsageResponse)
	err := c.cc.Invoke(ctx, DataCapService_ReportUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCapServiceClient) SyncDeviceState(ctx context.Context, in *DataCapSyncRequest, opts ...grpc.CallOption) (*DataCapSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataCapSyncResponse)
	err := c.cc.Invoke(ctx, DataCapService_SyncDeviceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataCapServiceServer is the server API for DataCapService service.
// All implementations must embed UnimplementedDataCapServiceServer
// for forward compatibility.
type DataCapServiceServer interface {
	ReportUsage(context.Context, *DataCapUsageBatch) (*ReportUsageResponse, error)
	SyncDeviceState(context.Context, *DataCapSyncRequest) (*DataCapSyncResponse, error)
	mustEmbedUnimplementedDataCapServiceServer()
}

// UnimplementedDataCapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataCapServiceServer struct{}

func (UnimplementedDataCapServiceServer) ReportUsage(context.Context, *DataCapUsageBatch) (*ReportUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUsage not implemented")
}
func (UnimplementedDataCapServiceServer) SyncDeviceState(context.Context, *DataCapSyncRequest) (*DataCapSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncDeviceState not implemented")
}
func (UnimplementedDataCapServiceServer) mustEmbedUnimplementedDataCapServiceServer() {}
func (UnimplementedDataCapServiceServer) testEmbeddedByValue()                        {}

// UnsafeDataCapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataCapServiceServer will
// result in compilation errors.
type UnsafeDataCapServiceServer interface {
	mustEmbedUnimplementedDataCapServiceServer()
}

func RegisterDataCapServiceServer(s grpc.ServiceRegistrar, srv DataCapServiceServer) {
	// If the following call panics, it indicates UnimplementedDataCapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataCapService_ServiceDesc, srv)
}

func _DataCapService_ReportUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataCapUsageBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCapServiceServer).ReportUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCapService_ReportUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCapServiceServer).ReportUsage(ctx, req.(*DataCapUsageBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCapService_SyncDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataCapSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCapServiceServer).SyncDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataCapService_SyncDeviceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCapServiceServer).SyncDeviceState(ctx, req.(*DataCapSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataCapService_ServiceDesc is the grpc.ServiceDesc for DataCapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataCapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lantern_cloud.api.DataCapService",
	HandlerType: (*DataCapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportUsage",
			Handler:    _DataCapService_ReportUsage_Handler,
		},
		{
			MethodName: "SyncDeviceState",
			Handler:    _DataCapService_SyncDeviceState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tracker/datacap/dcpb/datacap.proto",
}
